sudo: false
language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
    -

script: 
   - npm test
   - sbt clean coverage test

 

after_success: 
  - sbt coveralls
  - npm run coverage
  - npm run coveralls

notifications:
  email:
    recipients:
      - vokeolomu@yahoo.com